---
title: "Millenial Development Goals Database Explorer"
author: "John DeBlase"
date: "May 10, 2016"
output: html_document
---

### **Overview**

In 2000, world leaders in the UN agreed upon a set of seven development goals for humanity in order to undermine poverty, hunger and disease in underdeveloped nations. These goals also included improving social conditions such as equal opportunities for women and better education for children. Targets and indicators for each of the seven goals were selected by statisticians to measure progress toward the broader millenial development goals from 1990 - 2015.  

The Millenial Development Goals Database Explorer is an application designed to explore relationships and spot trends among several distinct MDG indicators across different target categories of disease(Tuberculosis rates), air quality (CO2 emmisions/Ozone depleting substances) and poverty(slum population/under-nourishment percentages).  

By making this app I am hoping to gain insight as to which countries and regions suffer from the highest overall tuberculosis rates, lowest air quality, and highest poverty percentages. Do the MDG indicators of these countries and regions show improvement over the course of the study (between 1990 -2013)? Is there an overall reduction of these problems on a world-wide level?

Finally, I want to explore any relationships between the three targets. Is there a correlation between incidence and death rates of TB rates and air quality or between TB ratesquality of living?


#### **MDG Indicator Information**

The metadata information for each indicator below is provided by the MDG Indicator Database website: <a href="http://mdgs.un.org/unsd/mdg/Metadata.aspx"> http://mdgs.un.org/unsd/mdg/Metadata.aspx </a> 

- **Tuberculosis death rate**. Refers to the estimated number of deaths due to tuberculosis (TB). The indicator reflects the number of deaths per 100,000 population per year. 

- **Tuberculosis incidence rate**. The estimated number of new tuberculosis (TB) cases arising in one year per 100,000 population.

- **Carbon dioxide emissions (CO2), thousand metric tons of CO2 (CDIAC)**. Amount of CO2 emmissions as monitored globally by the Carbon Dioxide Information Analysis Center.

- **Consumption of all Ozone-Depleting Substances in ODP metric tons**. This indicator is used to monitor the reduction in the usage of Ozone Depleting Substances (ODSs) measured using Ozone Depletion Potential, the amount of ozone depletion caused by a substance.

- **Consumption of ozone-depleting CFCs in ODP metric tons**. Similar to above but specifically measures the ODP in terms of chlorofluorocarbons, a specific category of ODS.

- **Population undernourished, percentage**. The undernourished or food deprived are those individuals whose food intake falls below the minimum level of dietary energy requirements.

- **Slum population as percentage of urban, percentage**. The Proportion of urban population living in slums is the proportion of urban population living in slum households. 


### **Data Acquisition and cleaning**

The original master csv was downloaded directly from the UN data mart site: <a href="http://data.un.org/DataMartInfo.aspx#MDG"> http://data.un.org/DataMartInfo.aspx#MDG</a>

My original plan was to upload this very large complete dataset into a MySQL database and from there query and transform the series data before loading the project dataset into R. This however proved to be infeasible due to major descrepencies in the formatting of the csv. Columns were misaligned throughout the dataset and metadata was mixed in with series data. For these reasons I decided that I needed do a preliminary cleaning of the dataset using a spreadsheet editor in order to realign columns and eliminate any extraneous metadata. From the spreadsheet editor I split and exported the data into 7 wide format csv files, one for each series indicator used in the project.

These csvs were then imported directly into R with the clean_data.R script and transformed using tidyr and dplyr. First, several extra blank columns were dropped from dataframes. Next, I used a function to transform the data from wide to long format and drop some extraenous columns. For tuberculosis data, only the midpoint observations were used, so the high and low observations were dropped from those dataframes. Finally, a union was peformed using rbind() in order to create a single long format clean master csv file that would serve as the backbone of the application.  

On application startup, the clean master csv is loaded and any rows containing missing observations were dropped using complete.cases() in order to improve the efficiency of the googleViz and ggplot libraries. A second dataset of country averages for each indicator is also created on startup for use with the Correlation Explorer component of the application.  

Link to data cleaning script and raw csv folder:
<a href="https://github.com/bsnacks000/MDG_data_explorer/tree/master/Cleaning"> github link </a>
 

#### **Application Design**

The application itself is divided into three sections: GeoChart, Data Explorer, and Correlation Explorer.

- **GeoChart** - an interactive map that is divided up into both world and regional views. The user can chart the progress of each indicator throughout the years spanning the study to get an overall sense of the MDG Indicator measurements for different regions/countries. 

- **Data Explorer** - this offers two distinct views, a set of sparklines for each MDG Indicator for a particular country and a filter chart that allows comparisons for up to 5 countries for each MDG Indicator. The sparklines view provides an overview for the basic trends for each country, while the filter chart allows a more detailed comparison between multiple countries.

- **Correlation Explorer** - an interactive scatterplot of avg values across all years for each MDG Indicator. Both the x and y axis are selectable to allow the user to look for correlations between any two MDG Indicators.

The application is designed to be fully scalable with the rest of the MDG dataset. This means that it can be potentially expanded to include more MDG Indicators without having to change any of the underlying server/ui code.


### **Insights / Exploratory Analysis**

_Which countries/regions are most affected by tuberculosis, air pollution, and poor living conditions? Do these regions show improvement over the course of the study?_

The regions most affected by high TB rates as well as poor living conditions are countries in southern Africa and southeast Asia, particularly in underdeveloped countries. The max TB death rate has been in steady decline worldwide since 1990, while the incidence rate has been increasing steadily. This could be an indication that although medicine has been helping treat TB once diagnosed, measures to prevent the spread of TB have been much less effective.

The countries with some of the highest TB rates and poorest living conditions include Nigeria, Somalia, Chad, Cambodia, Myanmar and Gabon. Overall these countries show a reduction in TB rates and slum/under-nourished percentages since 1990.

Several leading industrial nations are responsible for producing the majority of the world's air pollutants. These nations include China, United States, Russia, Japan and India. CO2 emissions have been steadily increasing in both the US and China since 1990. Since 1995 however, and excepting China, production of Ozone depleting substances have decreased substantially in these countries. 


_Is there any correlation between TB rates and either air quality or poverty conditions?_

Using the average rates amongst nations worldwide for each of the MDG Indicators a strong positive correlation can be shown between TB incidence/death rates and both slum to urban percantages as well as population under-nourished percentage. Countries with higher TB rates tend to on average have populations that suffer from poor living conditions and under-nourishment. 

The data also shows a slightly negative correlation between TB rates and air quality indicators. This is due to the fact that air pollutants are mostly produced by first world regions and nations, which have a higher standard of healthcare regarding TB.








